spring:
  config:
    activate:
      on-profile: cloud

  cloud:
    aws:
      s3:
        bucket: tanple-bucket
      stack.auto: false
      region.static: ap-northeast-2
      credentials:
        accessKey: <발급받은 accessKey>
        secretKey: <발급받은 secretKey>