spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tanple
    username: sa
  security:
    user:
      name: username
      password: userpassword
      roles: ADMIN, USER
springdoc:
  swagger-ui:
    path: /docs
  show-login-endpoint: true