spring:
  profiles:
    active: datasource, security
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  swagger-ui:
    path: /docs
  show-login-endpoint: true