spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/tanple
    username: sa
  security:
    user:
      name: username
      password: userpassword
      roles: ADMIN, USER
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
springdoc:
  swagger-ui:
    path: /docs
  show-login-endpoint: true